### ISSUE TITLE
pd-l2ork package() error: 'bin/cyclist': No such file or directory

### ISSUE THREAD

**Issue by korakinos** [agraef/aur-pkgbuilds#1]
Hi, as already stated on the AUR page, building pd-l2ork fails on my system. 
- pkgver: 1680.a49a2bb
- build command: makepkg and pacaur (tried both)
- error: 

```
==> Starting package()...
mv: cannot stat 'bin/cyclist': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```

Full build log attached. 

[buildlog.txt](https://github.com/agraef/aur-pkgbuilds/files/303168/buildlog.txt)

**Comment by agraef** [comment]
Might be a missing dependency. Can you please check whether you have package glib2 installed?

**Comment by agraef** [comment]
Also, make sure that you have the en_US locale installed. There's a bunch of messages like these in your log which I suspect to be the root issue for some other things that go awry in your build:

`/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US)`

**Comment by korakinos** [comment]
1. glib2 is installed (checked by `pacman -Qi glib2`).
2. Sorry for the confusion, but that's not the source of the error. Locale en_US.utf8 is installed (shows up in `locale -a`), though for the purposes of this bug report, I had mistakenly overridden my user locale to en_US (not en_US.utf8) when running the `makepkg` command. I had run it once before without changing the locale, and that time the error message did not show up (but the build failed nonetheless).

**Comment by agraef** [comment]
I need to have a clean build log, otherwise I'll be doing just guesswork. So please make sure that you get rid of any leftovers of the previous build under `/tmp/yaourt-tmp-*` and have your locale configured properly, before you rerun the build. Actually, I'd like to suggest that you create the build log from `makepkg` as follows, so that I can compare it to my own log more easily:

```
yaourt -G pd-l2ork
cd pd-l2ork
makepkg 2>&1 | tee buildlog.txt
```

Anyway, let's have a look at your buildlog as it is. I see the following build errors in there, which I don't see on any of my systems:

```
configure: WARNING: Required library 'flite' not found
configure: WARNING: - is the directory containing the 'flite' library in your LDFLAGS variable?
configure: error: Required library not found: aborting
```

That seems to point to a broken installation of the flite-fpic package. Please check that /usr/lib/libflite.a exists and that it contains the `flite_init` routine:  `nm /usr/lib/libflite.a | grep flite_init`. 

Next is this error:

```
./configure.gnu: 19: ./configure.gnu: Syntax error: "(" unexpected (expecting ";;")
configure: error: ./configure.gnu failed for gfsm
```

I'm not sure why that happens, but this _could_ possibly be caused by a shell which is confused about its locale and thus parses the script incorrectly. Also, please check that the file /home/abs/pd-l2ork/src/pd-l2ork/externals/moocow/gfsm/gfsm/configure.gnu looks ok. Line 19 should read:

```
    args=("${args[@]}" "CFLAGS=$axsf_safe") ##-- only retain 'safe' flags for gfsm
```

Which looks ok to me, and the configure of moocow/gfsm also works fine on my system. But on your system it fails, which then in all likelihood causes the next error:

```
Failed to open '../gfsm/gfsm.pc': No such file or directory
No package '../gfsm/gfsm.pc' found
In file included from ./atom_alphabet.h:32:0,
                 from atom_alphabet.c:28:
../gfsm/src/libgfsm/gfsm.h:40:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
```

At which point it bails out of the compilation of the externals, so cyclone never gets compiled. And that's why the build of your package eventually fails.

**Comment by korakinos** [comment]
Thank you very much for the analysis! Even more so as it appears very likely that the fault is in my system, not the PKGBUILD. And sorry for the messed-up build log. Compiling pd-l2ork takes hours on my computer, that's why I initially didn't bother running it again just because of the locale error. I did it now, with the same result as before. ~~I can post the log again, but I want to check something else first:~~

~~I noticed that for some reason I don't have the vanilla `flite` package from AUR installed, but `flite-fpic`. Maybe that's the source of the error? (`nm /usr/lib/libflite.a | grep flite_init` outputs `0000000000000000 T flite_init`.) I am compiling the former right now, and then I am going to try to makepkg pd-l2ork one more time. I'll post again in a few hours or tomorrow.~~

Wait, pd-l2ork depends on flite-fpic, not flite, so that's alright apparently. Hmm... I'll try reinstalling flite-fpic then.

**Comment by korakinos** [comment]
Reinstalling flite from AUR fixed the first error, but the build still fails due to the second (the gfsm "configure" one). Build log attached.

Now I suspect that it could be due to bashisms in the build scripts, as I have linked /bin/sh to dash, not bash. Running the build again with /bin/sh linking to bash now.

[buildlog2.txt](https://github.com/agraef/aur-pkgbuilds/files/305234/buildlog2.txt)

**Comment by agraef** [comment]
> Compiling pd-l2ork takes hours on my computer, that's why I initially didn't bother running it again just because of the locale error.

Yeah, it takes quite a while on my system, too. L2Ork, like the former Pd-Extended, is a huge, unwieldy package, because it contains an abundance of externals, and the build system really needs an overhaul. But it's also the most complete (and now that Pd-Extended isn't maintained any longer, in fact the only) "batteries included" Pd flavor.

Maybe I should revive the "vanilla" Pd-L2Ork package which just contains the basic Pd-L2Ork system without all the addons. I once did such a package for Ubuntu. The advantage is that it builds much faster, and it's often good enough if you don't need all the externals in the full version.

> Now I suspect that it could be due to bashisms in the build scripts, as I have linked /bin/sh to dash, not bash. Running the build again with /bin/sh linking to bash now.

Sounds plausible. I'm keeping my fingers crossed. Let me know how it goes.

Concerning the flite-fpic vs. flite issue: flite-fpic is a stupid name for the package, it should really be named flite1 (I didn't create the package, just took it over after it was orphaned). The flite package, OTOH is actually version 2 of flite. I think that the flite external really needs flite version 1 (at least that's what it uses on Ubuntu), but I never actually tested whether it also works with flite version 2.

**Comment by korakinos** [comment]
> Maybe I should revive the "vanilla" Pd-L2Ork package which just contains the basic Pd-L2Ork system without all the addons. I once did such a package for Ubuntu. The advantage is that it builds much faster, and it's often good enough if you don't need all the externals in the full version.

Sounds good, but I cannot competently comment on that because I am a Pure Data beginner and don't know yet which addons I need.

Bashisms: Yes, that was it, build successfull! So for now, the workaround is to manually make sure that a call of `/bin/sh` invokes bash, not dash, when building pd-l2ork. Maybe there is a way to do this in the PKGBUILD, so that no more people go into this trap?

**Comment by agraef** [comment]
> So for now, the workaround is to manually make sure that a call of /bin/sh invokes bash, not dash, when building pd-l2ork. Maybe there is a way to do this in the PKGBUILD, so that no more people go into this trap?

I don't see any way to do this which doesn't involve going through all the build scripts and patching them accordingly, which is a royal pita and might break the build when upstream changes.

I guess the lesson from this is that I should start providing binaries again. I used to have pd-l2ork in my Pure repositories at http://pureaur.bitbucket.org, and I'm currently working on adding it again.

**Comment by korakinos** [comment]
I am really not any good as shell scripting, but I was wondering if one could use an alias for that – but apparently aliases cannot contain slashes, so no "/bin/sh". Not so easy to override an absolute path… as it should be, I guess.

Binaries would be extremely convenient of course, if you really want to make that much effort. (I am not sure if my case alone warrants that, but I won't stop you.)

Thank you again!

**Comment by agraef** [comment]
No problem. Binaries will be ready soon.
